using JetBrains.Annotations;

namespace template.net10.api.Persistence.Models.Interfaces;

/// <summary>
///     Base marker interface that all persistence entities must implement.
///     Provides a default <see cref="Check"/> validation method.
/// </summary>
[UsedImplicitly(ImplicitUseTargetFlags.WithInheritors | ImplicitUseTargetFlags.WithMembers)]
internal interface IEntity
{
    /// <summary>
    ///     Performs a basic validity check on the entity.
    /// </summary>
    /// <returns><see langword="true"/> if the entity is considered valid; otherwise <see langword="false"/>.</returns>
    public bool Check()
    {
        return true;
    }
}

/// <summary>
///     Extends <see cref="IEntity"/> to expose a typed primary key <typeparamref name="TKey"/>.
/// </summary>
/// <typeparam name="TKey">The value-type used as the primary key (e.g. <see cref="short"/>, <see cref="int"/>).</typeparam>
internal interface IEntityWithId<TKey> : IEntity where TKey : struct
{
    /// <summary>
    ///     The unique primary key of the entity.
    /// </summary>
    TKey Id { get; init; }
}

/// <summary>
///     Extends <see cref="IEntity"/> for entities that carry an external Datahub identifier.
/// </summary>
internal interface IEntityWithDatahubId : IEntity
{
    /// <summary>
    ///     The identifier used to correlate this entity with an external Datahub resource.
    /// </summary>
    short DatahubId { get; init; }
}

/// <summary>
///     Extends <see cref="IEntity"/> for entities that expose a globally unique UUID.
/// </summary>
internal interface IEntityWithUuid : IEntity
{
    /// <summary>
    ///     The globally unique identifier of the entity, generated by the database (<c>gen_random_uuid()</c>).
    /// </summary>
    public Guid Uuid { get; init; }
}

/// <summary>
///     Extends <see cref="IEntity"/> for entities that have a mutable display name.
/// </summary>
internal interface IEntityWithName : IEntity
{
    /// <summary>
    ///     The mutable name of the entity.
    /// </summary>
    string Name { get; set; }
}

/// <summary>
///     Extends <see cref="IEntity"/> for entities whose name acts as an immutable natural key.
/// </summary>
internal interface IEntityWithNameKey : IEntity
{
    /// <summary>
    ///     The immutable name used as a unique natural key (e.g. role name, claim name).
    /// </summary>
    string Name { get; init; }
}

/// <summary>
///     Extends <see cref="IEntity"/> for entities that carry a human-friendly alias or display text.
/// </summary>
internal interface IEntityWithAlias : IEntity
{
    /// <summary>
    ///     A human-friendly alias or display label for the entity.
    /// </summary>
    string AliasText { get; set; }
}